<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-20T15:36:57 AEST" name="Suite" finished-at="2024-07-20T15:37:23 AEST" duration-ms="25445">
    <groups>
    </groups>
    <test started-at="2024-07-20T15:36:57 AEST" name="Test" finished-at="2024-07-20T15:37:23 AEST" duration-ms="25445">
      <class name="qa.test.MainTest">
        <test-method is-config="true" signature="beforeTestMethod()[pri:0, instance:qa.test.MainTest@56620197]" started-at="2024-07-20T15:36:57 AEST" name="beforeTestMethod" finished-at="2024-07-20T15:36:58 AEST" duration-ms="96" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestMethod -->
        <test-method is-config="true" signature="beforeMethod_Method(java.lang.String,java.lang.reflect.Method)[pri:0, instance:qa.test.MainTest@56620197]" started-at="2024-07-20T15:36:58 AEST" name="beforeMethod_Method" finished-at="2024-07-20T15:37:07 AEST" duration-ms="9660" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void qa.test.MainTest.LoginTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod_Method -->
        <test-method retried="true" signature="LoginTest()[pri:0, instance:qa.test.MainTest@56620197]" started-at="2024-07-20T15:37:07 AEST" name="LoginTest" finished-at="2024-07-20T15:37:10 AEST" duration-ms="2676" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element is not Present expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element is not Present expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at pageEvents.LoginPageEvents.checkLoginButtonPresent(LoginPageEvents.java:16)
at qa.test.MainTest.LoginTest(MainTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method is-config="true" signature="afterMethod_Method(org.testng.ITestResult)[pri:0, instance:qa.test.MainTest@56620197]" started-at="2024-07-20T15:37:10 AEST" name="afterMethod_Method" finished-at="2024-07-20T15:37:10 AEST" duration-ms="424" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginTest status=SKIP method=MainTest.LoginTest()[pri:0, instance:qa.test.MainTest@56620197] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod_Method -->
        <test-method is-config="true" signature="beforeMethod_Method(java.lang.String,java.lang.reflect.Method)[pri:0, instance:qa.test.MainTest@56620197]" started-at="2024-07-20T15:37:10 AEST" name="beforeMethod_Method" finished-at="2024-07-20T15:37:20 AEST" duration-ms="9371" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void qa.test.MainTest.LoginTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod_Method -->
        <test-method signature="LoginTest()[pri:0, instance:qa.test.MainTest@56620197]" started-at="2024-07-20T15:37:20 AEST" name="LoginTest" finished-at="2024-07-20T15:37:22 AEST" duration-ms="2577" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element is not Present expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element is not Present expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at pageEvents.LoginPageEvents.checkLoginButtonPresent(LoginPageEvents.java:16)
at qa.test.MainTest.LoginTest(MainTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method is-config="true" signature="afterMethod_Method(org.testng.ITestResult)[pri:0, instance:qa.test.MainTest@56620197]" started-at="2024-07-20T15:37:22 AEST" name="afterMethod_Method" finished-at="2024-07-20T15:37:23 AEST" duration-ms="414" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginTest status=FAILURE method=MainTest.LoginTest()[pri:0, instance:qa.test.MainTest@56620197] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod_Method -->
        <test-method is-config="true" signature="afterTestMethod()[pri:0, instance:qa.test.MainTest@56620197]" started-at="2024-07-20T15:37:23 AEST" name="afterTestMethod" finished-at="2024-07-20T15:37:23 AEST" duration-ms="124" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTestMethod -->
      </class> <!-- qa.test.MainTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
